In [1]:
import pandas as pd
import numpy as np
import os

%matplotlib inline
import matplotlib as plt

The data from the df below is the basis list of the stocks that I will be using the for built of the traded bot.

In [2]:
df = pd.read_csv("data/SP500Data.csv")

In [3]:
df.head()

,NUMBER,TICKER,NAME,MARKET CAP,STOCK PRICE,%CHANGE,REVENUE
0,1,AAPL,Apple Inc.,"3,915.30B",259.02,0.0032,391.04B
1,2,NVDA,NVIDIA Corporation,"3,426.89B",139.93,-0.0021,113.27B
2,3,MSFT,Microsoft Corporation,"3,257.30B",438.11,-0.0028,254.19B
3,4,GOOG,Alphabet Inc.,"2,408.66B",197.10,-0.0024,339.86B
4,5,GOOGL,Alphabet Inc.,"2,394.34B",195.60,-0.0026,339.86B

Below is the code for the creation of all the Excel files. I just added the Excel formula to each Excel file, and opening the app clicked enter for the formula to update (could have been done with another script.)

In [4]:
for tick in df["TICKER"]:
    dfTick = pd.DataFrame(['=STOCKHISTORY("%s", "1980-01-01", "2024-12-25",0,0,0,1,2,3,4,5)'%tick])
    #dfTick.to_csv(path_or_buf="data/SP500Data/%s.csv"%tick, header=False, index=False) ###DON'T RUN
    break

Below I decided to add the column names and make the date column the 'index column'. A couple of problems I went through were the appearance of euro marks in the Excel files, also there were some problems with the regex and the column names being converted to floats, this happened because the column names were added multiple times, so I needed to go through the first Excel file which is basically a test/trial file and update again to erase the column names. the try and except clauses are just for weird symbols that might appear in the Excel files.

In [5]:
df = pd.DataFrame
directory = os.fsencode("data/SP500Data")
for file in os.listdir(directory):
    filename = os.fsdecode(file)
    df = pd.read_csv("data/SP500Data/%s"%filename, names=("Date", "Close", "Open", "High", "Low", "Volume"), index_col="Date")
    try:
        df = df.replace("[^.0-9]", "", regex=True).astype(float)
    except(ValueError):
        continue
    df.to_csv(path_or_buf="data/SP500Data/%s"%filename)

I will try to make some exploratory analysis in the Excel files by combining them in one big dataframe with all the information, this exploratory analysis will be used to further understand the information that I collected (about 200mb). Then after the exploratory analysis I will clean the data from nulls and outlier values (the outlier values come from Excel sometime interpreting floating numbers as dates.)
I was having problems with a df having double headers for some reason, I just deleted that second row that was causing troubles.

In [6]:
directory = os.fsencode("data/SP500Data")
for file in os.listdir(directory):
    filename = os.fsdecode(file)
    df = pd.read_csv("data/SP500Data/%s"%filename)
    try:
        if df["Date"].iloc[0] == "Date":
            df.drop(0)
    except(UnicodeDecodeError, ValueError, TypeError):
        continue

Proof on correct concatenation which will be done in the following code cell.

In [51]:
df = pd.read_csv("data/SP500Data/ADM.csv")
df[df.isna().any(axis=1)].info()

<class 'pandas.core.frame.DataFrame'>
Index: 2948 entries, 0 to 2947
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    2948 non-null   object
 1   Close   2948 non-null   float64
 2   Open    0 non-null      float64
 3   High    2948 non-null   float64
 4   Low     2948 non-null   float64
 5   Volume  2948 non-null   float64
dtypes: float64(5), object(1)
memory usage: 161.2+ KB

I will add the rows that have null values throughout the entirety of Excel sheets (data) that I have, and try to understand what they have in common.

In [39]:
directory = os.fsencode("data/SP500Data")
dfNullVals = pd.DataFrame()
for file in os.listdir(directory):
    filename = os.fsdecode(file)
    df = pd.read_csv("data/SP500Data/%s"%filename)
    dfNullVals = pd.concat([dfNullVals, pd.DataFrame(df[df.isna().any(axis=1)])], axis=0)

In [45]:
dfNullVals.info()

<class 'pandas.core.frame.DataFrame'>
Index: 503760 entries, 0 to 2947
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Date    503760 non-null  object
 1   Close   502276 non-null  float64
 2   Open    2603 non-null    float64
 3   High    500484 non-null  float64
 4   Low     500483 non-null  float64
 5   Volume  497905 non-null  float64
dtypes: float64(5), object(1)
memory usage: 26.9+ MB

In [44]:
dfNullVals.head()

         Date  Close  Open  High  Low  Volume
0  11/23/2020    NaN   NaN   NaN  NaN     NaN
1  11/24/2020    NaN   NaN   NaN  NaN     NaN
2  11/25/2020    NaN   NaN   NaN  NaN     NaN
3  11/27/2020    NaN   NaN   NaN  NaN     NaN
4  11/30/2020    NaN   NaN   NaN  NaN     NaN

In [43]:
dfNullVals.describe()

               Close         Open           High            Low        Volume
count  502276.000000  2603.000000  500484.000000  500483.000000  4.979050e+05
mean        7.655573    76.550960       7.652038       7.493308  3.143113e+05
std        12.218188    77.449725      11.861633      11.597730  1.776960e+06
min         0.020000     0.020000       0.020000       0.020000  1.000000e+00
25%         2.000000    41.740000       2.020000       1.980000  2.000000e+04
50%         5.030000    58.060000       5.080000       4.970000  7.760000e+04
75%         9.560000   104.175000       9.630000       9.420000  2.258000e+05
max      3247.870000  3174.100000    3262.000000    3156.000000  3.955048e+08

After forming the big DataFrame with the null values found throughout the Excel sheet I can say that there is a really big amount of rows that did not have a proper opening value, most other columns are pretty complete

I will decide how to proceed on cleaning the data found by using the dfNullVals dataframe.

In [8]:
directory = os.fsencode("data/SP500Data")
for file in os.listdir(directory):
    filename = os.fsdecode(file)
    df = pd.read_csv("data/SP500Data/%s"%filename)