In [1]:
import pandas as pd
import numpy as np
import os

%matplotlib inline
import matplotlib as plt

The data from the df below is the basis list of the stocks that I will be using the for built of the traded bot.

In [39]:
df = pd.read_csv("data/SP500Data.csv")

In [40]:
df.head()

,NUMBER,TICKER,NAME,MARKET CAP,STOCK PRICE,%CHANGE,REVENUE
0,1,AAPL,Apple Inc.,"3,915.30B",259.02,0.0032,391.04B
1,2,NVDA,NVIDIA Corporation,"3,426.89B",139.93,-0.0021,113.27B
2,3,MSFT,Microsoft Corporation,"3,257.30B",438.11,-0.0028,254.19B
3,4,GOOG,Alphabet Inc.,"2,408.66B",197.10,-0.0024,339.86B
4,5,GOOGL,Alphabet Inc.,"2,394.34B",195.60,-0.0026,339.86B

Below is the code for the creation of all the Excel files. I just added the Excel formula to each Excel file, and opening the app clicked enter for the formula to update (could have been done with another script.)

In [41]:
for tick in df["TICKER"]:
    dfTick = pd.DataFrame(['=STOCKHISTORY("%s", "1980-01-01", "2024-12-25",0,0,0,1,2,3,4,5)'%tick])
    dfTick.to_csv(path_or_buf="data/SP500Data/%s.csv"%tick, header=False, index=False)
    break

Below I decided to add the column names and make the date column the 'index column'. A couple of problems I went through were the appearance of euro marks in the Excel files, also there were some problems with the regex and the column names being converted to floats, this happened because the column names were added multiple times, so I needed to go through the first Excel file which is basically a test/trial file and update again to erase the column names. the try and except clauses are just for weird symbols that might appear in the Excel files.

In [60]:
df = pd.DataFrame
directory = os.fsencode("data/SP500Data")
for file in os.listdir(directory):
    try:
        filename = os.fsdecode(file)
        df = pd.read_csv("data/SP500Data/%s"%filename, names=("Date", "Close", "Open", "High", "Low", "Volume"), index_col="Date")
        df = df.replace("[^.0-9]", "", regex=True).astype(float)
        df.to_csv(path_or_buf="data/SP500Data/%s"%filename)
    except(UnicodeDecodeError, ValueError, TypeError):
        continue

I will try to make some exploratory analysis in the Excel files by combining them in one big dataframe with all the information, this exploratory analysis will be used to further understand the information that I collected (about 200mb). Then after the exploratory analysis I will clean the data from nulls and outlier values (the outlier values come from Excel sometime interpreting floating numbers as dates.)

In [61]:
df.head()

          Close   Open   High    Low      Volume
Date
2/1/2013  31.01  31.50  31.74  30.47  66789484.0
2/4/2013  31.02  31.09  31.99  30.76   7695943.0
2/5/2013  31.04  31.25  31.98  30.85   5014316.0
2/6/2013  31.03  30.98  31.43  30.75   2126101.0
2/7/2013  32.00  31.00  32.73  31.00   3800770.0